### ISSUE TITLE
Автозум форума при установке курсора в текстовое поле на мобильных устройствах

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#104]
Открываем форум (мобильный или декстопный вид не важен) на мобильном устройстве в портретном режиме
Ставим курсор в текстовое поле, появляется клавиатура и происходит автозум форума
![image](https://user-images.githubusercontent.com/13614247/36944210-2e3ed244-1fa0-11e8-818b-955076a16db7.png)
![image](https://user-images.githubusercontent.com/13614247/36944213-33270b32-1fa0-11e8-8a38-c374c12f7722.png)
так как при скрытии клавиатуры зум не возвращается на место, то такое поведение нужно превентить, тем более что это чуть ли не единственный сайт, где я такое наблюдаю, плюс размеры элементов у нас ок даже для маленьких мобил и зум не нужен вообще

**Comment by rekcuFniarB** [comment]
Помню обсуждали в чате, думал что уже фиксил. Пофикшено теперь в 34406b3d320f4913a69169cca04c31298d4fafb3.

А вторая картинка это старая? Вроде такого съезжания полей сейчас быть не должно.

**Comment by DJ-ZX** [comment]
Так пофиксилось, что сломал вид всего
![Image](https://i.imgur.com/OfayUSF.jpg)
![Image](https://i.imgur.com/YGtMA1e.jpg)

**Comment by rekcuFniarB** [comment]
Мда, придётся больше кода написать для исправления ширины полей. Но размер текста придётся оставить такой, т.к. в iOS зачем-то принудительно зумят если размер текста в полях ввода меньше 16px.

**Comment by DJ-ZX** [comment]
потому что иос говно, но тем не менее надо под неё адаптироваться... эххх..

**Comment by rekcuFniarB** [comment]
Отправил какой-то фикс (a9987d7ef4e5a8a608799e354f3e29cb0030f290), проверь не ломаются ли теперь другие поля ввода и закрой.

**Comment by DJ-ZX** [comment]
![Image](https://i.imgur.com/E46yJn8.jpg)
Обрезается комбобокс (везде) остальное ок

**Comment by rekcuFniarB** [comment]
Ок, пофиксил вроде.

**Comment by DJ-ZX** [comment]
подтверждаю, ты не закрывай сам баги если чо - я ж проверяю после тебя )))
