### ISSUE TITLE
Встраивание Телеграм постов

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#112]
Формат кода

`<script async src="https://telegram.org/js/telegram-widget.js?4" data-telegram-post="ZXBeer/247" data-width="100%"></script>`
вид такой
![image](https://user-images.githubusercontent.com/13614247/44961608-45cbf000-af14-11e8-86b6-8ed42371a8c9.png)

**Comment by rekcuFniarB** [comment]
* Ни у кого почти работать не будет, т.к. это говно забанено.
* Нет смысла эту хрень эмбедить, это не аудио/видео. Информация, встраиваемая таким образом, не доступна для поиска ни по форуму, ни для Гугла. Они не видят этого встраиваемого текста, потому что он физически не на нашем сайте.
* Предлагаемый код встраивания говно. Это Дуров такой код придумал? Он или дурак, или очень хитрожопый. Такой скрипт получает полный доступ к странице и может творить что угодно. Когда встраивается через `<iframe>` хоть какая-то изоляция контента есть, браузер не позволяет стороннему сайту вылезти за пределы фрейма. Вообще у них есть вариант эмбеддинга с помощью `<iframe>`: `<iframe width="640" height="480" src="https://t.me/ZXBeer/247?embed=1"></iframe>`, т.е. аналог в BB коде это `[media=640,480]https://t.me/ZXBeer/247?embed=1[/media]`. Но как я уже сказал выше, эту хрень почти никто не увидет, ибо забанено.
