### ISSUE TITLE
Уменьшить шрифт в "выявленых никах" в мобильном виде и запретить форме вылазить за границы окна

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#113]
Скриншот очевиден вроде, не вижу смысла расписывать
![image](https://user-images.githubusercontent.com/13614247/45187731-095d0480-b232-11e8-86e3-bab10cd6dbb9.png)

**Comment by rekcuFniarB** [comment]
Fixed.
