### ISSUE TITLE
Переместить поле ввода комментариев под список, а не над ним

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#122]
Сабж

**Comment by rekcuFniarB** [comment]
Done 2b0c740d2b38547eed2bf7a449943b1e82991806

**Comment by rekcuFniarB** [comment]
Зачем? Иначе чтобы оставить новый комментарий придётся прокручивать страницу к начало комментов чтобы нажать кнопку "комментировать".

У кнопки блокировки отдельный issue, я этим не занимался ещё.

**Comment by DJ-ZX** [comment]
нет, смотри:
![image](https://user-images.githubusercontent.com/13614247/48514002-9f7a6000-e85d-11e8-80bc-17a0f8aba406.png)
сча так
![image](https://user-images.githubusercontent.com/13614247/48514030-b0c36c80-e85d-11e8-99bc-c11f7eafa4e7.png)
то есть кнопка "комментариев (хх)" - это формально кнопка сворачивания треда (плюсик) и она должна быть по всем критериям дизайна - сверху сворачиваемого треда, то есть так
![image](https://user-images.githubusercontent.com/13614247/48514255-3e9f5780-e85e-11e8-9194-31926b2d8f2d.png)

**Comment by DJ-ZX** [comment]
либо второй вариант - ПОД полем ввода коммента, но никак не между текстом и полем ввода

и ещё - пофиксь это убогое "комментариев (7)" , просто пусть будет "Комментарии (17; 9354 симв. ост.) или чот такое, но точно не "комментариев"

**Comment by rekcuFniarB** [comment]
А какой смысл было тогда вносить изменения, если по прежнему надо прокручивать страницу чтобы нажать кнопку? "Критерии дизайна" идут нафиг, главный критерий это удобство.

**Comment by DJ-ZX** [comment]
не, не идут
поле ввода внизу логично должно быть либо над, либо под ПОСЛЕДНИМ комментарием
кнопка сворачивания треда тут никаким боком не относится, но её точно нужно мувать вне основной зоны, и кстати, тоже нужно как то логично отделить, тоненькой полоской или хз как, чтобы не мешалась

**Comment by DJ-ZX** [comment]
и кстати мне лично неудобно, я вверх тянусь для сворачивания треда в любом норм софте, а тут я сначала начал вверх скакать, а потом заметил, что она внизу

**Comment by rekcuFniarB** [comment]
Блин, я всё время забываю что у тебя свёрнутые комменты. Короче, в дефолтном виде я оставлю как есть, там по нажатию кнопки "комментировать" под ней появляется форма ввода коммента, после отправки она исчезает.

**Comment by DJ-ZX** [comment]
ничиво не понимаю, сделай так как сча, просто тайтл не мувай, в чём проблема то? у кого каменты развёрнуты всё равно будут переходить вниз и так и так

**Comment by rekcuFniarB** [comment]
Короче, для свёрнутых комментов переместил кнопку раскрытия назад вверх, раз тебе неудобно. Для развёрнутых комментов текущее положение наоборот норм.

**Comment by DJ-ZX** [comment]
всё равно не норм НАД полем ввода, тогда под поле помести

**Comment by rekcuFniarB** [comment]
Нет, в режиме развёрнутых комментов кнопка "комментировать" отображается в самом низу, при её нажатии появляется поле. Это как раз соответствует твоим "критериям дизайна", т.к. в отличие от режима свёрнутых комментов, здесь эта кнопка разворачивает не комменты, а форму ввода.

**Comment by DJ-ZX** [comment]
так, стоп, сча я пойду потестить, но мне немного кажется дичью, сча гляну

**Comment by DJ-ZX** [comment]
потестил, ты неправ
поясняю:
![image](https://user-images.githubusercontent.com/13614247/48515938-714b4f00-e862-11e8-97b9-78aa9044b663.png)
(это десктоп на планшете или не фуллскрине, на мобильном будет тоже самое)
![image](https://user-images.githubusercontent.com/13614247/48515969-80ca9800-e862-11e8-84b7-6aeba940f487.png)
читаю я комент Аида, кликаю по привычке кнопку "комментировать" и получаю поле вода и курсор в нём, кнопка комментов остаётся на месте
второй вариант: 
![image](https://user-images.githubusercontent.com/13614247/48516073-c8512400-e862-11e8-803d-0d1ebbf341cb.png)
нажимаю "комментировать" и поле разворачивается "вверх" под текст, с фокусом:
сча ты разворачиваешь вниз и у тя текст "комментировать" миксуется с контентом, что фейл

разворачивать поле вверх ок тема, это никак дизайну не противоречит

**Comment by rekcuFniarB** [comment]
Ой всё :F

**Comment by DJ-ZX** [comment]
ещё запили вызов панели смайлов к комментам

**Comment by rekcuFniarB** [comment]
Давно думал, но мне лично оно не особо нужно, поэтому забил. Оформи отдельную ишшую, если очень надо. Может когда сделаю.

**Comment by rekcuFniarB** [comment]
Ну теперь-то всё? :D Закрывай.

**Comment by DJ-ZX** [comment]
ты сделал разворачивание вверх?

**Comment by rekcuFniarB** [comment]
В режиме развёрнутых комментов переместил форму над кнопкой "комментировать".

**Comment by DJ-ZX** [comment]
проверил, мне нра
