### ISSUE TITLE
Чат радио поломан

### ISSUE THREAD

**Issue by rekcuFniarB** [rekcuFniarB/forum-theprodigy-ru#141]
После обновления сервера чат сломался, т.к. PHP теперь запускается по другому: используется связка apache-mod-fcgi (документация apache рекомендует этот вариант для php-fpm) + php-fpm, но в таком случае там какая-то принудительная буферизация ответа и сервер ничего не отдаёт, пока не заполнится буфер или не завершится работа скрипта. Функции `ob_flush()` и `flush()` не помогают.
Вроде как буферизация эта происходит на стороне Apache и если верить обсуждению, отключить пока нельзя (в будущих версиях говорят будет можно).

Есть идея временного костыля, например заполнять оставшийся буфер нулями `\0` при выдаче новых сообщений из чата. Но то такое себе...

**Comment by DJ-ZX** [comment]
а можно к новогоднему эфиру пофиксить на всяк случай?

**Comment by rekcuFniarB** [comment]
Ах да, уже. https://github.com/rekcuFniarB/forum-theprodigy-ru/tree/master/utils/UnixSocket2Websocket#readme

**Comment by rekcuFniarB** [comment]
Кстати, работать стало ещё лучше чем было, сообщения вообще стали мгновенно ходить.
