### ISSUE TITLE
Запретить границам форума выходить за границы экранов, а тексту не вписываться в размеры статичных форм (в первую очередь в мобильном виде)

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#143]
на иОС и в МакОС сафари воспроизводится проще андроида и винды, но тоже реально

![image](https://user-images.githubusercontent.com/13614247/72895843-a8e34000-3d1e-11ea-88d9-79fc2ebb878f.png)

![image](https://user-images.githubusercontent.com/13614247/72894498-bc40dc00-3d1b-11ea-9ae4-77b9539a4348.png)

**Comment by rekcuFniarB** [comment]
> на иОС и в МакОС сафари 

Давайте ещё ZX Spectrum поддерживать :D

**Comment by rekcuFniarB** [comment]
Посмотрел код, там и так прописано правило разбивать строки. Почему сафари это не делает, это уже к ним.

В хроме работает как положено:
![screenshot](https://i.imgur.com/8pAhXwF.jpg) ![screenshot](https://i.imgur.com/krMBuC7.jpg)

**Comment by DJ-ZX** [comment]
движок ВебКит (который не хромиум) юзается на куче девайсов, знач нам не помешало бы поддерживать

**Comment by DJ-ZX** [comment]
кстати, речь не только в разбивании строк, вот тут хорошо видно в принципе, что и другие элементы вылазят за границы
![image](https://user-images.githubusercontent.com/13614247/73120478-b4c54100-3f6e-11ea-90f5-6195b70261c5.png)

**Comment by rekcuFniarB** [comment]
>движок ВебКит (который не хромиум) юзается на куче девайсов, 
На давно не поддерживаемых разве что, все давно перешли на [Blink](https://ru.wikipedia.org/wiki/Blink_(%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA)).

>  вот тут хорошо видно в принципе, что и другие элементы вылазят за границы

Там не баг, формой отправки сообщенния в принципе никто не занимался ещё, там тупо дефолт и отмеченное на скриншоте регулируется CSS правилом `box-sizing: border-box`.

**Comment by DJ-ZX** [comment]
ты не можешь делать втд что устройств от эппл не существует, уверен на форум многие ходят с разных эплодевайсов

**Comment by rekcuFniarB** [comment]
А я тут причём? Я прописал правило разбивать строки, а дальше не мои проблемы, в имеющихся у меня браузерах работает. Кому прям очень надо, пусть сами дебажат под кривые клиенты, у меня и поважней дела есть чем проблемы меньшинств ![ ;\] ](https://forum.theprodigy.ru/Skins/Arenabulance/YaBBImages/trollface.gif "trollface")

**Comment by rekcuFniarB** [comment]
https://example.com/aaaaa/bbbb/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by rekcuFniarB** [comment]
Нашёл в репозитории какой-то дурацкий браузер Epiphany на webkit из состава Gnome. Суть проблемы в том что в webkit кое какие элементы почему-то не наследуют правила родительских элементов как в нормальных движках. Пришлось продублироваь правило для них. Решает ли это проблему в гейоси ХЗ, в этом браузере пофиксилось.

Косяки со второго скриншота не воспроизвелись, но с ними сейчас заморачиваться нет смысла, если всё равно есть задача переверстать эту часть (вынос части элементов в другое место или как там... #123 )

А вообще я еб-л татить много времени на эти задротские маразмы.
