### ISSUE TITLE
Увеличить отступ между блоками кое где

### ISSUE THREAD

**Issue by rekcuFniarB** [rekcuFniarB/forum-theprodigy-ru#148]
Например между постами в результатах поика и между постами в ленте, а то сливаются, читать неудобно таки.
Может ещё где-то.

**Comment by DJ-ZX** [comment]
Не  может быть, а я ж говорил 😂

**Comment by rekcuFniarB** [comment]
> Не может быть, а я ж говорил

Чего ты говорил? Ленту и страницу поиска мы не обсуждали вообще. Это не про мобильный вид.
