### ISSUE TITLE
Исправить тег [news]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rekcuFniarB/forum-theprodigy-ru#19]
```
При наличии тега в посте содержимое поста 
не отображается совсем.

http://forum.theprodigy.ru/1320724

```

Original issue reported on code.google.com by `retratserif@gmail.com` on 21 Feb 2015 at 7:52

**Comment by rekcuFniarB** [comment]
Закрываю из-за отсутствия новых данных, т.к. тегом никто не пользуется.

**Comment by DJ-ZX** [comment]
Перепроверю сначала

**Comment by rekcuFniarB** [comment]
Там какая-то проблема один раз возникла при неопределённых условиях. Потом отловить так и не удалось.
