### ISSUE TITLE
Unicode не отображается в заголовках сообщений в Личных Сообщениях

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rekcuFniarB/forum-theprodigy-ru#44]
```
отображается

Без темыывчядллоавдлыоа 
&#217;&#216;&#214;&#212;&#208;&#230;&#232;&#234;

вместо ÙØÖÔÐæèê

--
тело поста корректно отображает
```

Original issue reported on code.google.com by `djzx.z...@gmail.com` on 9 Mar 2015 at 10:49

**Comment by DJ-ZX** [comment]
кстати, на самом деле не тысячи и некоторые не-юникод софты умеют в такое преобразование
но мне чото кажется, что это пофикшено, можешь проверить?

**Comment by rekcuFniarB** [comment]
Проверил, в заголовках не пофикшено. Можно конечно и там вставить костыль, но лучше после обновления PHP конвертануться в utf-8 и убрать все костыли.

**Comment by rekcuFniarB** [comment]
Оно само случайно когда-то пофиксилось после каких-то других фиксов. Правда из-за того что юникод нативно не поддерживается, а реализовано это костылями, есть потенциальные проблемы...
