### ISSUE TITLE
Добавить линк-кнопку для переключения между десктопным и мобильным видом

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#53]
Собственно как принято на большинстве сайтов:
в конце страницы "Перейти в дектопный/мобильный вид" линком

**Comment by rekcuFniarB** [comment]
Сделано.

**Comment by DJ-ZX** [comment]
а чтобы увидеть нужно кэш чистить?

**Comment by DJ-ZX** [comment]
перемести переключалку над баннером-счётчиком

**Comment by rekcuFniarB** [comment]
> перемести переключалку над баннером-счётчиком

Уверен? Imho то что в самом низу удобно, если надо, прокрутил страницу до конца и всё.

**Comment by DJ-ZX** [comment]
уверен, я чуть не ебанулся её искать, я бы даже над подписью с копирайтом бы сунул

**Comment by DJ-ZX** [comment]
и что такое компактный вид? поменяй на мобильный.

**Comment by rekcuFniarB** [comment]
А что такое «мобильный вид»? Выражение не имеет смысла, вид не может быть мобильным. А вот «компактный вид» всё понятно о чём речь :-D

**Comment by DJ-ZX** [comment]
ты ща траллишь меня? "десктопный" и "мобильный" - это альтернативы
десктопный и компактный - это вообще не противоречие, десктопный может быть компактным, а мобильный - расширенным. но мы ваще-то именно мобильный вид делаем, кароч не тролль. никто не пишет "компактный никогда", во всех браузерах - desktop view/mobile view

**Comment by rekcuFniarB** [comment]
> десктопный может быть компактным,

Так никто и не запрещает использовать это на десктопе. 

> никто не пишет "компактный никогда", во всех браузерах - desktop view/mobile view

Я знаю, но мы особенные :D

**Comment by DJ-ZX** [comment]
лишнехромосомные небось?

**Comment by rekcuFniarB** [comment]
Ок, переименовал и переместил.
