### ISSUE TITLE
Исправить наложение текста в нескольких местах мобильного вида

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#54]
![bug_mob1](https://cloud.githubusercontent.com/assets/13614247/16901480/cd76a95e-4c4d-11e6-91a3-12bcf38fe685.png)
выделено красным

**Comment by rekcuFniarB** [comment]
Кнопки уже не перекрывают статус.
Высоту бэкграунда шапки сообщения я чуть менял когда-то (и/или отступ текста от него), вроде в скине yabbse этой проблемы уже не было. Тем не менее, в разных скинах размеры чуть отличаются и где-то может быть норм, где-то отступ больше. Надо перепроверить и возможно закрыть.

**Comment by rekcuFniarB** [comment]
Вроде не актуально, после каких-то правок исправилось.
