### ISSUE TITLE
Исправление форматирования поля комметрирования и разделителей между блоками (пост/комменты, страницы, действия, последние, ответ)

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#55]
![12898868fe2b4d6b3b5a51e6f72f4b7087275b58008db472d7 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/13614247/16901487/3dea7dc8-4c4e-11e6-848a-6ac41a637e0f.jpg)
[16.07.2016 12:29:36] Roman Gorin: 2. Реализация поля комментирования должна быть, как у Джына - по центру и на всю ширину, только калькулятор не нужно убирать - оба счётчика перенести под поле ввода и "отправить" рядом, либо оставить, как сейчас, но всё равно - по центру и на всю ширину поле + счётчик для поля ввода.
[16.07.2016 12:36:46] Roman Gorin: 4. реализация блоков кнопок имхо у брейна лучше, хотя при определённом зуме есть риск получить 2 иконки во второй строке, но зато у брейна иконки зумом не распидорашивает по умолчанию
5. "показать хз сколько комментов" строчки форматнуть по центру или по правому краю, никак не вразнобой

**Comment by DJ-ZX** [comment]
нужно вернуться к этим багам и зафиксить, обсуждали в чате

**Comment by DJ-ZX** [comment]
хотя бы отцентрировать в первую очередь, а то тут тоже как везде, но понизил приоритет

**Comment by rekcuFniarB** [comment]
Ок, сделано в одну линию для обоих режимов.

**Comment by DJ-ZX** [comment]
шик, а можно вместо тайтла "отправить" поставить чото типа **>>**
или как в телеграме/скайпе и иже иконку вместо текста
![image](https://user-images.githubusercontent.com/13614247/26953888-c80a99b2-4cb5-11e7-8054-f4ec2ac98959.png)
![image](https://user-images.githubusercontent.com/13614247/26953892-ced3dd6c-4cb5-11e7-86ef-2df00884daa2.png)

**Comment by DJ-ZX** [comment]
и почему, кстати, кнопка "запереть" рядом с отправить? её бы рядом с "подписаться" показывать, не?

**Comment by rekcuFniarB** [comment]
> плюс терь имеющиеся комменты по ширине поля ввода, а не экрана

Где такое происходит?

**Comment by rekcuFniarB** [comment]
Блин, это проявляется в режиме свёрнутых комментов, пофикшу...

**Comment by DJ-ZX** [comment]
и ещё в пару к значку на кнопке "отправить" (реально - много текста для кнопки, которая по факту Enter дублирует) просто обрати внимание на ширину счётчика - явно на 1 символ больше, чем нужно, с учётом лимита в 256, можно уменьшить и ещё и шрифт сделать меньше (ну и align - по центру и вертикально и горизонтально) - тогда будет по красоте

**Comment by DJ-ZX** [comment]
Теперь комменты всегда развернутые ))) 

Плюс кнопка отправить почти идеал, но она меньше счетчика выглядит, оптимально либо одного размера, либо чуть больше. Скрин могу выслать

**Comment by rekcuFniarB** [comment]
ППЦ...

**Comment by DJ-ZX** [comment]
Кек)))

**Comment by DJ-ZX** [comment]
![wp_ss_20170609_0001](https://user-images.githubusercontent.com/13614247/26973640-184b3b74-4d20-11e7-8277-40d6ab52b533.png)
![wp_ss_20170609_0002](https://user-images.githubusercontent.com/13614247/26973641-184e09d0-4d20-11e7-8270-73c74126ac32.png)
Собственно вот так

**Comment by DJ-ZX** [comment]
![screenshot_20170609-154417](https://user-images.githubusercontent.com/13614247/26976066-ffca5836-4d2a-11e7-95c5-7282d8770608.png)
А ещё в Хроме лажа выравнивание из-за иконки замка (похоже на это)

**Comment by DJ-ZX** [comment]
всё, что выше - пофикшено, но вылез новый баг
после отправки коммента поле ввода исчезает
![image](https://user-images.githubusercontent.com/13614247/27000702-9ac56340-4dc0-11e7-85d0-9f80ab8f8c38.png)
и появляется только если свернуть комменты
![image](https://user-images.githubusercontent.com/13614247/27000707-af582e64-4dc0-11e7-8155-b4853889a596.png)
и кстати, скажи - будешь переносить замок в этом баге или запилить тебе отдельный чисто на перенос замка и счётчика для 10000 символов (от всех комментов)?

**Comment by rekcuFniarB** [comment]
Ок, пофиксил исчезновение формы.

> будешь переносить замок в этом баге или запилить тебе отдельный чисто на перенос замка и счётчика для 10000 символов (от всех комментов)?

Не буду переносить вообще, оставлю как есть.

**Comment by DJ-ZX** [comment]
Тогда напишу имеет ибо тихо он там не нужен (не только в мобильном виде, а ваще)

**Comment by rekcuFniarB** [comment]
Закрываю тогда, раз всё. В мобильном хроме не проверял правда, запускать его лень, он у меня заблеклищен ибо неубиваем.
