### ISSUE TITLE
Внедрить скрипт от Diag для ресайза картинок

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#57]
https://yadi.sk/d/BgRDsupBtM4WY
Там кусок, который сжимает картинки по ширине продублирован в $(document).ready() и в $(window).load(), и, если мне не изменяет память, нормально он будет работать только на $(window).load(), потому что док.реади вызывается, когда картинки еще не загружены (чтобы узнать их размер)

**Comment by rekcuFniarB** [comment]
Написал свой вариант, только я пошёл другим путём. У Диага скрипт пробегает по всем изображениям на странице и высчитывает им ширину. Я же решил при клике по изображениям открывать попап с изобажением в ширину экрана.  За одно миниатюры radikal и funkyimg так же разворачиваются вместо того чтобы открывалась новая вкладка с просмотром изображения на сайте хостинга изображения (в будущем можно добавить обработку миниатюр других подобных хостингов изображений).
