### ISSUE TITLE
Исправить Layout для просмотра заценок

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#59]
![screenshot_2016-07-30-10-57-34](https://cloud.githubusercontent.com/assets/13614247/17272733/fa9f68fe-56a6-11e6-8eb7-5e3777d06313.png)
![screenshot_2016-07-30-10-57-42](https://cloud.githubusercontent.com/assets/13614247/17272732/fa9c1924-56a6-11e6-8294-9201a8b0a43a.png)

**Comment by rekcuFniarB** [comment]
Fixed

**Comment by DJ-ZX** [comment]
1. Большие промежутки между постами остались
2. Кнопки "топ 10" не открывают список в MS Edge
3. заголовок "юзернейм поощрил - перейти к сообщению" никак не отделён (фоном, как в темах форума) от текста, а лучше именно заголовок оставить, а сообщение сделать сворачиваемым

скриншоты приложу через час-плотора

**Comment by rekcuFniarB** [comment]
> Кнопки "топ 10" не открывают список в MS Edge

Там эти кнопки идентичные, у них никак не может быть разное поведение.

> а лучше именно заголовок оставить, а сообщение сделать сворачиваемым

Ок, попробую (вроде я сам это и предлагал когда-то :D ) ...

**Comment by rekcuFniarB** [comment]
> Кнопки "топ 10" не открывают список в MS Edge

Не так прочитал, подумал что какие-то открываются, какие-то нет. Тут исправлять нечего, либо забить болт на Edge, либо не сворачивать эти списки. Кстати, тогда и разворачивание постов таким образом работать не будет в Edge.

**Comment by DJ-ZX** [comment]
Забить на Эдж не варик, но сворачивание в теге или сворачивание блока комментов работает. Тут же происходит открытие, сразу клик на первый ник и закрытие с открытием страницы юзера первого в списке.
Это явный баг.

**Comment by rekcuFniarB** [comment]
> но сворачивание в теге

Спойлер что ли? Там JS.

> или сворачивание блока комментов работает.

Там JS.

**Comment by rekcuFniarB** [comment]
> ут же происходит открытие, сразу клик на первый ник и закрытие с открытием страницы юзера первого в списке.

А, так бы сразу и сказал. Это не то чтобы баг, у меня тоже иногда получалось.  Наверное можно решить проблему увеличением высоты заголовка «Топ 10».

**Comment by DJ-ZX** [comment]
ну я воспроизвёл его 5 из 5-и и это не тру

**Comment by rekcuFniarB** [comment]
Чекай.
Увелисил высоту кнопок "Топ10", посты ограничил по высоте, разворачиаются при клике, уменьшил промежутки между постами.

**Comment by DJ-ZX** [comment]
сделал новую ишшую по исправлению того, что сделано тут, эту закрываю до времени, когда будут идеи как сделать лучше
