### ISSUE TITLE
Нельзя приаттачить 2 аттача вместе или даже подряд в соседних постах

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#65]
При выборе аттачмента - можно выбрать только один файл. Было бы не проблемой, но из-за объединения постов если написать пост - приаттачить файл, потом второй и зааттачить другой файл, то второй файл не аттачится. Чтобы запостить нужно ждать таймаута пока посты не будут не объединяться.

**Comment by DJ-ZX** [comment]
причём если подождать паузу и попробовать передобавить не отображающуюся картинку то вылетает меседж:
"Извините ! Имя файла уже используется. Пожалуйста, переименуйте файл и попробуйте снова."

**Comment by rekcuFniarB** [comment]
Это потому что объединённый пост физически это один обычный пост, а более одного аттачмента там не предусмотрено. Решение — не показывать форму вставки файла если пост будет объединён.

**Comment by DJ-ZX** [comment]
лучше не объединять посты, если выбран аттачмент

**Comment by rekcuFniarB** [comment]
Тоже норм вариант.

**Comment by DJ-ZX** [comment]
И это актуально

**Comment by rekcuFniarB** [comment]
fixed 86a8b75126e579ed3f9e3549d008f910af84edf1

**Comment by rekcuFniarB** [comment]
Так я утром откатил назад временно, т.к. кое что сломалось правками что были до.

**Comment by rekcuFniarB** [comment]
Всё, вернул патч. При загрузке файла слияния постов не должно происходить.
