### ISSUE TITLE
Откатить в мобильном виде сворачивание списков покаравши/поощривших и постов в просмотре заценок

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#66]
обсуждалось, так что сабж
пока не работает как надо на всех основных браузерах - пусть будут полные посты

**Comment by DJ-ZX** [comment]
![wp_ss_20160821_0002](https://cloud.githubusercontent.com/assets/13614247/23143404/f2838802-f7c9-11e6-8349-47a841587cdf.png)

**Comment by DJ-ZX** [comment]
Up

**Comment by rekcuFniarB** [comment]
Откачено.
