### ISSUE TITLE
Исправить мобильный вид страницы объединения тем

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#81]
Сабж, скрин
![wp_ss_20170506_0002](https://cloud.githubusercontent.com/assets/13614247/25780733/d45994e6-3335-11e7-9016-4d37e5ec1126.png)

**Comment by DJ-ZX** [comment]
Кнопку "Соединить темы" сделать по общему стилю кнопок в мобильном виде (с окантовкой)

**Comment by rekcuFniarB** [comment]
Fixed
cba747cfe52320600171aab36dbae75d2d79a606 
5b6d34e3de159e0217c2d3ed60812dcc03894d93
2776c4d38fa97f9b9bbb10d39c8cacb961f1969d
