### ISSUE TITLE
Плейлисты с Youtube встраиваются только через тег "media", а должны через тег "y/youtube"

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#82]
Пример
https://forum.theprodigy.ru/1357714
во-первых, не подходит ссылка из страницы плейлиста
1) https://www.youtube.com/playlist?list=PLmwDbIbyjhHlKTWt8Xh-WtDcDn7JN81Ca или же из адресной строки во время воспроизведения
2) https://www.youtube.com/watch?list=PLmwDbIbyjhHlKTWt8Xh-WtDcDn7JN81Ca&v=S4ElN3l8oos (ведёт на первое видео)
в тег медиа нужно помещать ссылку из src
<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLmwDbIbyjhHlKTWt8Xh-WtDcDn7JN81Ca" frameborder="0" allowfullscreen></iframe>

во-первых, судя по всему сгенерить ссылку для эмбеда из ссылок 1 или 2 не особо проблема
во-вторых, нужно, чтобы это обрабатывалось тегом ютюба ибо логично, либо автоконвертировать в тег медиа при наличии "list=" в ютюб ссылке

**Comment by DJ-ZX** [comment]
из этих трёх после коммита стал работать только последний

https://www.youtube.com/embed/videoseries?list=PL15ty5GYCv5uaX7hoMOCxYdOh4jDfukW5

https://www.youtube.com/playlist?list=PLmwDbIbyjhHlKTWt8Xh-WtDcDn7JN81Ca

https://www.youtube.com/watch?list=PLmwDbIbyjhHlKTWt8Xh-WtDcDn7JN81Ca

**Comment by rekcuFniarB** [comment]
Ну первый логично что не работает, это для встраивания фреймов напрямую (в нашем случае это тег [media]).

Второй линк он откуда вообще взялся, Ютуб такие выдаёт даёт?

**Comment by DJ-ZX** [comment]
а кликнуть не пробовал? )))

**Comment by DJ-ZX** [comment]
моя идея была в том, что тег ютюба может получать "list=PL15ty5GYCv5uaX7hoMOCxYdOh4jDfukW5" и конвертить всегда в полноценное видео, а не всовывать [y][/y]

**Comment by rekcuFniarB** [comment]
Так по ссылке нет плеера даже, только список видео.

**Comment by rekcuFniarB** [comment]
https://www.youtube.com/watch?list=PLmwDbIbyjhHlKTWt8Xh-WtDcDn7JN81Ca

Этот линк вообще невалидный, редиректит на главную. Где ты его взял?

**Comment by DJ-ZX** [comment]
а, точно, игнорь его

**Comment by rekcuFniarB** [comment]
Пофикшено несколько дней назад.
