### ISSUE TITLE
Текст в попапах (например, в удалённых сообщениях) невозможно выделить

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#83]
![image](https://cloud.githubusercontent.com/assets/13614247/26286436/1ac3b946-3e6e-11e7-9b36-6ac6df124cb4.png)
текст невозможно выделить мышью или тапом внутри попапа (MS Edge, Chrome/Opera - без разницы)

при этом на мобиле можно выделить тапом

**Comment by rekcuFniarB** [comment]
Раз последствий не выявлено то закрываю как fixed.

**Comment by DJ-ZX** [comment]
да, у меня тож всё ок
