### ISSUE TITLE
Улучшить функцию бана (все в одном)

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#85]
1 - убрать поле под юзером, сделать диалог бана всплывающим окошком по кнопке/линку в профиле и также где-то тут
![image](https://cloud.githubusercontent.com/assets/13614247/26753473/b189df58-486f-11e7-97fa-eb301ff5ffe6.png)
2 - в диалог бана добавить галочку "Спамер" и требовать капчу или хотя бы двойное подтверджение, в котором будет сказано такое "все сообщения/комментарии пользователя будут удалены и пользователь будет забанен навсегда"
3 - при бане отправлять сообщение на почту пользователя
4 - при вечном бане отправлять уведомление в личку форума всем админам и юзерам "Пользователь такой-то забанен тем то с такой формулировкой", в случае галки "спамер" - только админам с реквестом на удаление и занесение почты в блеклист (если он у нас есть)
5 - добавить галку "бан по айпи", также требовать двойное подтверждение/каптчу
6 - добавить галку "Запросить добавление пользователя в блеклист/защиту от спама/ддос атак" (я имею ввиду "антисобаль").

всё реализовывать можно поэтапно, просто написал, чтобы не забыть, чото ещё вспомню - дополню, если что с чем пересекается - линкуйте

**Comment by DJ-ZX** [comment]
про логику знаю - это дополнение к тому тикету по функционалу
затем, что а) можно случайно забанить (серьёзно, пришёл писать человеку в личку и случайно нажал бан), б) реально легко спутать с личкой для глобов ))) (ну и да, это просто нелогично, бан должен быть отдельным окном, в данном случае это предложение, на случай "а вдруг"

про несколько человек - речь не в том, а что чистятся в основном спамеры и нужно сначала к ним в профайл пойти, потом ввести причину бана и т.д. ессесно кнопку именно в треды пилить только в случае реализации той же галки спамер и вызова диалога

"с кого" - с глобов/админов, чтобы риск ошибки при бане спамера с удалением постов был минимален, равно как и при бане по айпи ибо это целая подсеть
если ты низкоуровневую логику сделаешь иначе - тут можно будет изменить формат, я скорее обозначил суть

**Comment by rekcuFniarB** [comment]
> можно случайно забанить (серьёзно, пришёл писать человеку в личку и случайно нажал бан)

Ну там же подтверждение спрашивается и так, этого достаточно для защиты от случайных банов. Капча это уже перебор.

**Comment by DJ-ZX** [comment]
капча только в случае если галка "спамер" отмечена (что должно автоматом удалять все месседжи и комменты), если не отмечена, то пох, ессесно

**Comment by rekcuFniarB** [comment]
И всё равно не вижу смысла в капче, зачем? Во-вторых, считаю что возможность удалить все сообщения и комменты одним махом должно быть доступно только админу.

**Comment by DJ-ZX** [comment]
О, ты навел на мысль, отметка спамер должны отправлять письмо админам с подтверждением очистки всех сообщений. Поправлю главный пост пожже

**Comment by rekcuFniarB** [comment]
> О, ты навел на мысль, отметка спамер должны отправлять письмо админам с подтверждением очистки всех сообщений. Поправлю главный пост пожже

Лучше разрешить модерам самим это делать если пользователь зарегистрировался не более месяца назад (или недели). Комменты правда чистить геморно...

> при бане отправлять сообщение на почту пользователя

Уже реализовано.

**Comment by rekcuFniarB** [comment]
Вроде всё из этого уже реализовано в том или ином виде кроме [этого](https://github.com/rekcuFniarB/forum-theprodigy-ru/issues/101), что-то отброшено за ненадобностью. Чтобы зря не висело, вынес нереализованное в отдельный issue, этот закрываю.
