### ISSUE TITLE
Редактирование постов лагает или вообще не работает в мобильном виде

### ISSUE THREAD

**Issue by DJ-ZX** [rekcuFniarB/forum-theprodigy-ru#95]
Детали позже
По факту просто после нажатия Отправить - вечная или очень долгая (несколько минут) загрузка, но даж до обновления страницы не доходит иногда за 2-3 минуты

**Comment by rekcuFniarB** [comment]
Проблем не обнаружил. При редактировании своих постов? Вообще там не может быть никакой зависимости от мобильного режима, он не затрагивает бакенд никак, логика общая.

Воспроизводится всегда? А то могли быть какие нибудь временные глюки с сетью (для мобильной сети обычное явление) или временные тормоза на сервере.

**Comment by DJ-ZX** [comment]
я просто несколько раз наблюдал уже
этот баг я написал как раз в процессе когда висело редактирование в хроме
может лаги есть и вообще, но я не сталкивался, а с мобильным режимом стабильно почему-то, именно редактирование своих постов (других я и не пробовал), запрос уходит и долго висит

при этом новые посты без пауз уходят и баги в гитхаб пишутся норм, хз как отследить, но если дашь рекомендации как более активно логировать что происходит - попробую

**Comment by rekcuFniarB** [comment]
Ну для начала собери статистику при каких условиях это происходит. Везде, или только в мобильной сети или по вайфаю тоже, или может только на домашнем вайфае или только на работе или везде. Происходит ли это независимо от браузера.

На нашей стороне таким лагам происходить негде, единственное место где может произойти задержка это процесс записи в БД, но это может возникнуть только при условии что в данный момент сервер сильно перегружен (что бывает сейчас крайне редко, когда много ботов набегает), либо я замечал редкие тормоза сервера по вине хостинга (тупо тормозит дисковое I/O, такое мы наблюдали раньше в 00:30 каждые сутки).

**Comment by rekcuFniarB** [comment]
> а с мобильным режимом стабильно почему-то

И это странно, т.к. мобильный режим влияет только на то, подключается ли файл mobile.css, то есть к лагам это отношение иметь никак не может. То есть тут либо совпадение, либо происходит не из-за самого режима, а просто на мобиле (сеть лагает?).

Вобщем, если выяснится что это на нашей стороне лаги, то для поиска места лагов придётся прикручивать профилировщик (тут надо подумать как сделать так чтобы он активировался только когда ты редактируешь посты) и изучать логи...

**Comment by rekcuFniarB** [comment]
А ещё странность в том что у тебя лагает именно при редактировании, хотя там принципиальной разницы с постингом никакой.

**Comment by rekcuFniarB** [comment]
Т.к. новых подробностей не поступило, а вчера была устранена потенциальная причина таких лагов, закрываю.

Мобильный вид был не причём, просто совпадение. Лаги возникали скорей всего в момент когда периодически запускался скрипт очистки устаревших сессий, который сильно тормозил из-за особенностей ФС (директория может читаться медленно, если в ней когда-то побывало 100500 файлов).  Конкретно эта проблема решена пересозданием директории заново, теперь скрипт там выполняется быстро.

Хотя случайные лаги в разные моменты могут быть разные и не все из-за проблем на нашей стороне.
